spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/potatodb
    username: postgres
    password: 1234
    hikari:
      connectionTimeout: 20000
      maximumPoolsize: 10


