server:
  port: 8080
  servlet:
    context-path: '/'
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  config: classpath:log/log4j2.xml

spring:
  profiles:
    include: oauth #application-oauth.yaml
    active: local
  servlet:
    multipart: # 파일 첨부의 크기
      max-file-size: 20MB
      max-request-size: 20MB
      # JVM의 기본 임시디렉토리에 권한이 없어서 일단 여기로 설정
      # 기본 임시디렉토리는 System.out.println(System.getProperty("java.io.tmpdir"));
      location: C:\github_potato\potato\src\main\resources\upload\temp_images

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: com.tft.potato.config.PostgreSQLCustomDialect
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
          #provider_disables_autocommit: true
          provider_disables_autocommit: false # 이 설정때문에 jparepo save가 동작을안함 왜지?
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        #generate_statistics: true
        jdbc:
          batch_size: 10000
        order_inserts: true
        order_updates: true
    generate-ddl: false


file:
  upload:
    #images-dir: ./uploads/images #프로젝트의 루크 디렉토리 및 ex) /Users/developer/project/uploads
    images-dir: C:\github_potato\potato\src\main\resources\upload\images # linux에서는 \ 대신 /를 쓴다.



